### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '__initialized') when microapp created in Reactjs

### ISSUE THREAD

**Issue by prafull-opensignlabs** [SurjitSahoo/cra-mf#14]
hey can you help me with this issue 

Error :

`getOrLoadRemote.js:22 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__initialized')
    at getOrLoadRemote.js:22:1
    at Generator.next (<anonymous>)
    at getOrLoadRemote.js:7:1
    at new Promise (<anonymous>)
    at __awaiter (getOrLoadRemote.js:3:1)
    at HTMLScriptElement.<anonymous> (getOrLoadRemote.js:19:1)`

Steps to reproduce:
https://medium.com/@surjitsahoo0/dynamic-module-federation-in-react-js-create-react-app-2b77fdaff3ab
follow steps for this blog create microapp in react js not in react ts

Note: when I try with typescript it works fine

**Comment by prafull-opensignlabs** [comment]
I have resolved this issue 
There is no problem with code. I haven't pass correct remote name  that's why this issue was occur
